<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.javi.master</groupId>
    <artifactId>spark_project</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>streaming</module>
        <module>batch</module>
        <module>shared</module>
    </modules>

    <profiles>
        <profile>
            <id>dev</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>

        <profile>
            <id>prod</id>
            <properties>
                <conf.dir>prod</conf.dir>
            </properties>
        </profile>
    </profiles>


    <properties>
        <conf.dir>dev</conf.dir>
        <scala.version>2.12.17</scala.version>
        <scala.short.version>2.12</scala.short.version>
        <spark.version>3.5.1</spark.version>
        <kafka.version>3.9.1</kafka.version>
        <scalatest.version>3.2.18</scalatest.version>
        <spark.testing.base.version>3.4.0_0.15.0</spark.testing.base.version>
        <log4j2.version>2.20.0</log4j2.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- Dependencias principales -->
            <dependency>
                <groupId>org.scala-lang</groupId>
                <artifactId>scala-library</artifactId>
                <version>${scala.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.spark</groupId>
                <artifactId>spark-core_${scala.short.version}</artifactId>
                <version>${spark.version}</version>
                <scope>compile</scope>
<!--                <exclusions>-->
<!--                    <exclusion>-->
<!--                        <groupId>commons-io</groupId>-->
<!--                        <artifactId>commons-io</artifactId>-->
<!--                    </exclusion>-->
<!--                </exclusions>-->
            </dependency>
            <dependency>
                <groupId>org.apache.spark</groupId>
                <artifactId>spark-sql_${scala.short.version}</artifactId>
                <version>${spark.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.spark</groupId>
                <artifactId>spark-sql-kafka-0-10_${scala.short.version}</artifactId>
                <version>${spark.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.kafka</groupId>
                <artifactId>kafka-clients</artifactId>
                <version>${kafka.version}</version>
            </dependency>
            <!-- https://mvnrepository.com/artifact/org.mongodb.spark/mongo-spark-connector -->
            <dependency>
                <groupId>org.mongodb.spark</groupId>
                <artifactId>mongo-spark-connector_${scala.short.version}</artifactId>
                <version>10.4.1</version>
            </dependency>
            <!-- Typesafe Config for external conf loading -->
            <dependency>
                <groupId>com.typesafe</groupId>
                <artifactId>config</artifactId>
                <version>1.4.3</version>
            </dependency>
            <!-- Dependencias de testing -->
            <dependency>
                <groupId>org.scalatest</groupId>
                <artifactId>scalatest_${scala.short.version}</artifactId>
                <version>${scalatest.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>com.holdenkarau</groupId>
                <artifactId>spark-testing-base_${scala.short.version}</artifactId>
                <version>${spark.testing.base.version}</version>
                <scope>test</scope>
            </dependency>
            <!-- https://mvnrepository.com/artifact/org.scalatestplus/mockito-4-11 -->
            <dependency>
                <groupId>org.scalatestplus</groupId>
                <artifactId>mockito-4-11_${scala.short.version}</artifactId>
                <version>3.2.18.0</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>de.flapdoodle.embed</groupId>
                <artifactId>de.flapdoodle.embed.mongo</artifactId>
                <version>4.21.0</version>
                <scope>test</scope>
            </dependency>
            <!-- https://mvnrepository.com/artifact/org.mongodb.scala/mongo-scala-driver -->
            <dependency>
                <groupId>org.mongodb.scala</groupId>
                <artifactId>mongo-scala-driver_${scala.short.version}</artifactId>
                <version>5.3.1</version>
                <scope>test</scope>
            </dependency>
            <!-- Logging -->
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-api</artifactId>
                <version>${log4j2.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-core</artifactId>
                <version>${log4j2.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.logging.log4j</groupId>
                <artifactId>log4j-slf4j-impl</artifactId>
                <version>${log4j2.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-core</artifactId>
                <version>2.15.2</version>
            </dependency>
        </dependencies>

    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.1.2</version>

                <configuration>
                    <useSystemClassLoader>false</useSystemClassLoader>
<!--                    <skipTests>false</skipTests>-->
                    <includes>
                        <include>**/*Test.*</include>
                        <include>**/*Spec.*</include>
                        <include>**/*Suite.*</include>
                    </includes>
                    <systemPropertyVariables>
                        <java.awt.headless>true</java.awt.headless>
<!--                        <de.flapdoodle.os.override>Linux|X86_64|CentOS|CentOS_9</de.flapdoodle.os.override>-->
                    </systemPropertyVariables>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.alchim31.maven</groupId>
                <artifactId>scala-maven-plugin</artifactId>
                <version>4.8.1</version>
                <executions>
                    <execution>
                        <id>scala-compile</id>
                        <goals>
                            <goal>compile</goal>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <scalaVersion>${scala.version}</scalaVersion>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.7</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <excludes>
                        <exclude>**/*Test*</exclude>
                        <exclude>**/*Spec*</exclude>
                        <exclude>**/target/**</exclude>
                    </excludes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                    <execution>
                        <id>copy-resources</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.outputDirectory}/conf</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.basedir}/../conf/${conf.dir}</directory>
                                    <filtering>true</filtering>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>