  inputRelativePath = "data/json/input/"
#   spark {
#     driver {
#     memory = "1g"
#         }
#     executor {
#         memory = "1g"
#         }
#      jars {
#         packages = "org.mongodb.spark:mongo-spark-connector_2.12:10.4.1"
#      }
#     }
mongodb {
    output {
        uri = "mongodb://localhost:27017"
        database = "elmercado"
        collection = "articulos"
    }
}
