# Root logger
rootLogger.level = WARN
rootLogger.appenderRef.stdout.ref = console

# Spark logging
logger.spark.name = org.apache.spark
logger.spark.level = WARN

# Project logging
logger.project.name = org.javi.master
logger.project.level = INFO

# Console appender
appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} [%t] %-5p %c{1}:%L - %m%n
