spark {
  mongodb {
  input {
    uri = "mongodb://localhost:27017"
    database = "elmercado"
    collection = "articulos"
    }
  }
  }
  checkpointLocation = "/tmp/streaming-checkpoint"
  kafka {
  bootstrap {
  servers = "localhost:29092"
  }
  topic {
  input = "streaming-query"
  output = "output"
  }
  }
