#spark {
#
#  }
  checkpointLocation = "/tmp/streaming-checkpoint"
mongodb {
  input {
    uri = "mongodb://localhost:27017"
    database = "elmercado"
    collection = "articulos"
    }
  }

kafka {
 bootstrap {
  servers = "localhost:29092"
 }
 topic {
  input = "streaming-query"
  output = "output"
 }
}
