streaming {
  mongo {
    uri = "mongodb://masternode:27017"
    database = "elmercado"
    collection = "articulos"
  }
  checkpointLocation = "/tmp/streaming-checkpoint"
  kafka {
  bootstrap {
  servers = "localhost:9095"
  }
  topic {
  input = "streaming-query"
  output = "output"
  }
;     localBootstrap = "localhost:9095"
;     clusterBootstrap = "workernode1:9092,workernode2:9093,workernode3:9094"
;     topic = "streaming-query"
  }
}
